logLevel: "INFO"
showFooter: false
showNavigation: true
checkForUpdates: false
actions:
  # Raspberry-Sprinkles
  - title: Run Schedule Adhoc
    icon: '<img src = "customIcons/schedule.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runschedule -d scheduleids=1,5,9,13,17
    timeout: 5

  - title: Stop
    icon: '<img src = "customIcons/stop.png" width = "48px" />'
    shell: curl -s -X DELETE http://127.0.0.1:5000/stoprunning
    timeout: 5

  - title: Rain Delay
    icon: '<img src = "customIcons/rain.png" width = "48px" />'
    shell: curl -s -X PATCH http://127.0.0.1:5000/raindelay
    timeout: 5

  - title: View Rain Delay
    icon: '<img src = "customIcons/status.png" width = "48px" />'
    shell: curl -s -X GET http://127.0.0.1:5000/raindelay
    timeout: 5

  - title: Remove Rain Delay
    icon: '<img src = "customIcons/cloud-remove.png" width = "48px" />'
    shell: curl -s -X DELETE http://127.0.0.1:5000/raindelay
    timeout: 5

  - title: Water Front Bed
    icon: '<img src = "customIcons/flowers.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runadhoc/1 -d runtime=6
    timeout: 5

  - title: Water Front Lawn
    icon: '<img src = "customIcons/grass.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runadhoc/2 -d runtime=6
    timeout: 5

  - title: Water Side Fence
    icon: '<img src = "customIcons/fence.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runadhoc/3 -d runtime=6
    timeout: 5

  - title: Water Back Fence
    icon: '<img src = "customIcons/fence-2.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runadhoc/4 -d runtime=6
    timeout: 5

  - title: Water Back Garden
    icon: '<img src = "customIcons/garden.png" width = "48px" />'
    shell: curl -s -X PUT http://127.0.0.1:5000/runadhoc/5 -d runtime={{ time }}
    timeout: 5
    arguments:
      - name: time
        choices:
          - title: 10 Minutes
            value: 10

          - title: 30 Minutes
            value: 30

          - title: 60 Minutes
            value: 60

  - title: PiWater Power On
    icon: '<img src = "customIcons/switch-on.png" width = "48px" />'
    shell: ssh olivetin@automation 'sudo salt-call event.send salt/beacon/iot/event/kasa-device device=\"iot-plug-piwater1\" state=\"on\"'
    timeout: 5

  - title: PiWater Power Off
    icon: '<img src = "customIcons/switch-off.png" width = "48px" />'
    shell: ssh olivetin@automation 'sudo salt-call event.send salt/beacon/iot/event/kasa-device device=\"iot-plug-piwater1\" state=\"softoff\"'
    timeout: 5